name: Storybook

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version'
        required: false
        type: string
        default: '24'
      pnpm_version:
        description: 'PNPM version'
        required: false
        type: string
        default: '11.13.0'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check .storybook directory
        run: |
          if [ ! -d .storybook ]; then
            echo "::error::Directory '.storybook' not found. Aborting pipeline."
            exit 1
          fi

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: ${{ inputs.pnpm_version || '11.13.0' }}

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node_version || '24' }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.minimumReleaseAge=0

      - name: Build Storybook
        run: pnpm storybook:build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: storybook-static

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      - name: Summary
        shell: bash
        run: |
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "![Storybook](https://img.shields.io/badge/-Storybook-FF4785?style=for-the-badge&logo=storybook&logoColor=white)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Storybook deployed" >> "$GITHUB_STEP_SUMMARY"
          echo "The Storybook is available at ${{ steps.deployment.outputs.page_url }}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
